server.port: 8083

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root

s3:
  endpointUrl: http://127.0.0.1:9000
  accessKey: NR10NO9XHZL2NLGH6U9U
  secretKey: K0kgnMmS/2+iaYozYrsjDI1SMfAliwNq6UzJxI7r
  bucketName: moviefun

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG